---
apiVersion: v1
kind: Service
metadata:
  name: test-app-svc
spec:
  selector:
    app: netology-test-app
  type: NodePort
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.deployment.appPort }}
    nodePort: {{ .Values.service.nodePort }}