---
apiVersion: v1
kind: Service
metadata:
  name: test-app-svc
  namespace: netology-test-app
spec:
  selector:
    app: netology-test-app
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
