---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-test-app
  namespace: netology-test-app
  labels:
    app: netology-test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netology-test-app
  template:
    metadata:
      labels:
        app: netology-test-app
    spec:
      containers:
      - name: netology-test-app
        image: cr.yandex/crppudjmh5lksthdg9q4/my_test:0.0.1
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
      imagePullSecrets:
      - name: myregistrykey 
